Document::download encoding fix
jlevers/selling-partner-api pull request #233
Opened 2022-03-25 22:06 UTC by 0xSekar

Fix for issue #231

2022-03-28 18:23 UTC, jlevers requested changes
Looks good -- just want an update on the relevant comment.

2022-03-28 18:23 UTC, jlevers commented on lib/Document.php
> +        // Documents encodings depend on target marketplace, which messes up the data when we read it directly
Please update this to say:

```php
// Document encodings depend on the target marketplace. English-language reports are
// typically ISO-8859-1 encoded, which messes up the data when we read it directly via
// SimpleXML or as a plain TAB/CSV, but the original encoding is required to parse XLSX
// and PDF reports.
```

2022-03-28 22:37 UTC, 0xSekar commented on lib/Document.php
> +        // Documents encodings depend on target marketplace, which messes up the data when we read it directly
Updated

2022-03-29 02:13 UTC, jlevers approved these changes
Looks great, thanks!

2022-03-29 02:13 UTC, merged